### PR TITLE
Delay required to allow sensor to come online.

### PR DESCRIPTION
**Pull request by ctgreybeard**
Symptom is a blue screen of nothingness

A single added delay statement during setup()

I encountered this while building the [Thermal Camera With Display](https://learn.adafruit.com/thermal-camera-with-display). The screen showed all blue. This fix was found in the forums.

### CODE REVIEW

**Comment by ladyada** [comment]
@deanm1278 heya can you check the DS if a delay is required and put it in the object begin() rather than here?
@ctgreybeard thanks for the fix, we're going to see if there's a root cause :)

**Comment by ctgreybeard** [comment]
Thanks, Limor, for all you do!

**Comment by deanm1278** [comment]
@ladyada @ctgreybeard yea it looks like the datasheet says:
`Setup Time Typ. 50msec（Time to enable Communication after Setup)`
Although it's never made clear what specifically constitutes 'Setup'...
I've added the delay to the end of begin https://github.com/adafruit/Adafruit_AMG88xx/commit/3b9b38625c8f704b756c749c9254f805e13a81ff

**Comment by ladyada** [comment]
thanks!

**Pull request closed without merging**
